### PR TITLE
Add manpage

### PR DESCRIPTION
**Pull request by antavelos**

### CODE REVIEW

**Review by creekorful — APPROVED** [review]

**Comment by creekorful** [comment]
This is really great, thank you :D

Did you write it by hand or with help2man?

**Comment by antavelos** [comment]
I wrote it by hand. Basically, I modified the `ls` manpage ;)

**Comment by creekorful** [comment]
Nice trick ;D

The package has been uploaded and is waiting for approval in the [NEW](https://ftp-master.debian.org/new/terminews_1.2.0-1.html) queue. It will take up to several weeks for the package to be manually reviewed by a member of the ftpteam.

Once it has been approved, I'll release a new package version with the manpage you wrote. Can you just please create a new release (tag) like 1.2.1 or even 1.3.0 to include your latest changes?

When packaging application on Debian we are aligning ourselves using upstream tag.

**Comment by antavelos** [comment]
Nice! Looking forward to the final approval.

In the meantime I've create a new [release](https://github.com/antavelos/terminews/releases/tag/v1.2.1).

Let me know if there is anything else you need from me.

Cheers!

**Comment by creekorful** [comment]
Thank you ! :)
I'll let you know once the package gets approved!

**Pull request merged**
